In [ ]:
from googleapiclient.discovery import build
import pandas as pd
from langdetect import detect_langs
from langdetect.lang_detect_exception import LangDetectException

In [2]:
api_key = "AIzaSyAMweCpx9L10WyMIBxqTLeQ_3uaeYKEmTw"
youtube = build('youtube', 'v3', developerKey=api_key)

In [ ]:
def get_comments(video_id, max_results=100, max_pages=3):
    comments = []
    next_page_token = None
    page_count = 0

    while True:
        request = youtube.commentThreads().list(
            part="snippet",
            videoId=video_id,
            maxResults=max_results,
            pageToken=next_page_token,
            textFormat="plainText"
        )
        response = request.execute()
        
        for item in response['items']:
            comment = item['snippet']['topLevelComment']['snippet']
            comments.append({
                #'author': comment['authorDisplayName'],
                'text': comment['textDisplay'],
                'likeCount': comment['likeCount'],
                'publishedAt': comment['publishedAt']
            })

        page_count += 1
        next_page_token = response.get('nextPageToken')
        if not next_page_token or page_count >= max_pages:
            break

    return pd.DataFrame(comments)

In [ ]:
video_id = "SbNDmAJBtyU" # https://youtu.be/SbNDmAJBtyU?si=9Fqc1fK7c1vYLkpS
df = get_comments(video_id, max_pages=99999)
df.to_csv("rawData/youtube_comments.csv", index=False)
print("Finished")

Finished

In [5]:
df

,author,text,likeCount,publishedAt
0,@AuroraVibes,*Where's everyone listening from?* ❤️\n\nYou c...,6344,2020-06-07T17:37:47Z
1,@SantoshiDeviDevi-w6p,Depression पर song है kya,1,2026-03-02T14:52:32Z
2,@Snorlaxziny,Quem tá aqui porque o Corinthians foi eliminado,0,2026-03-01T01:42:35Z
3,@BenceLakatos-q6o,Its ironic how pepole say only adults can have...,1,2026-02-16T01:10:12Z
4,@jerrycarmona2969,Wish my mind and consciousness could go dark w...,0,2026-02-03T06:51:11Z
...,...,...,...,...
16244,@manzy8106,Yes,3,2020-06-07T17:42:35Z
16245,@BLACKN-fq7fr,1,1,2020-06-07T17:42:34Z
16246,@mattfnx-3964,firsttt,1,2020-06-07T17:42:32Z
16247,@AuroraVibes,*Where's everyone listening from?* ❤️\n\nYou c...,6344,2020-06-07T17:37:47Z
16248,@AuroraVibes,"Tracklist for ""depressing songs for depressed ...",278,2020-06-07T17:35:04Z

In [6]:
df = df[df['text'].str.len() > 5]

In [ ]:
def safe_detect(text):
    try:
        if detect_langs(text)[0].lang == 'en' and detect_langs(text)[0].prob > 0.9:
            return detect_langs(text)
        else:
            return None
    except LangDetectException:
        return None

In [8]:
df['language'] = df['text'].apply(safe_detect)

In [9]:
df.head(20)

,author,text,likeCount,publishedAt,language
0,@AuroraVibes,*Where's everyone listening from?* ❤️\n\nYou c...,6344,2020-06-07T17:37:47Z,[en:0.999997530301607]
1,@SantoshiDeviDevi-w6p,Depression पर song है kya,1,2026-03-02T14:52:32Z,None
2,@Snorlaxziny,Quem tá aqui porque o Corinthians foi eliminado,0,2026-03-01T01:42:35Z,None
3,@BenceLakatos-q6o,Its ironic how pepole say only adults can have...,1,2026-02-16T01:10:12Z,[en:0.9999983291586645]
4,@jerrycarmona2969,Wish my mind and consciousness could go dark w...,0,2026-02-03T06:51:11Z,[en:0.9999983928726253]
5,@Mattie-x1l,And people are telling me oh it's way funner w...,2,2026-01-29T16:08:49Z,[en:0.9999952149153228]
6,@Mattie-x1l,My parents got divorced on my birthday and I h...,1,2026-01-29T16:06:49Z,[en:0.9999967725441328]
7,@clement9431,anyone,0,2026-01-26T12:59:05Z,None
8,@Rose-bl5ov,2026??? Anyone here,2,2026-01-24T11:10:14Z,None
9,@Rose-bl5ov,I feel lifeless,0,2026-01-24T10:46:49Z,None
10,@MikuLovelyGod,The Lord is close to the brokenhearted and sav...,0,2026-01-23T01:42:47Z,[en:0.9999957105506926]
11,@HenryHobbs-s1w,I feel like giving up with life rn 😢,0,2026-01-15T09:59:27Z,[en:0.9999966442810334]
12,@BrandonRoberts-n4d,I'm depressed right now,0,2026-01-10T23:19:17Z,[en:0.9999952903698525]
13,@foreverblackpinkandablink,"I'm just depressed and empty,numb,tired,hurt,l...",0,2025-12-29T21:26:07Z,[en:0.9999974189933801]
14,@ultrablue7477,"You could be listening to polkas, waltzes, and...",0,2025-12-22T20:45:51Z,[en:0.9999961525588492]
15,@ultrablue7477,"Remember the good old days, when the sun was b...",0,2025-12-22T20:30:06Z,[en:0.9999955892701531]
16,@ultrablue7477,Why is the media full of bad news?\nBecause fo...,0,2025-12-22T20:18:00Z,[en:0.9999955369353142]
17,@ultrablue7477,People and dogs get out of their way to watch ...,0,2025-12-22T20:11:50Z,[en:0.9999923444079778]
18,@ultrablue7477,People secretly love depression and drama.\nTh...,0,2025-12-22T20:08:59Z,[en:0.9999971390099278]
19,@ultrablue7477,Depression is awesome!!!!\nYou can write poetr...,0,2025-12-22T20:04:24Z,[en:0.9999980655854792]

In [10]:
df[df['language'].notnull()].reset_index(drop=True)[1:]

,author,text,likeCount,publishedAt,language
1,@BenceLakatos-q6o,Its ironic how pepole say only adults can have...,1,2026-02-16T01:10:12Z,[en:0.9999983291586645]
2,@jerrycarmona2969,Wish my mind and consciousness could go dark w...,0,2026-02-03T06:51:11Z,[en:0.9999983928726253]
3,@Mattie-x1l,And people are telling me oh it's way funner w...,2,2026-01-29T16:08:49Z,[en:0.9999952149153228]
4,@Mattie-x1l,My parents got divorced on my birthday and I h...,1,2026-01-29T16:06:49Z,[en:0.9999967725441328]
5,@MikuLovelyGod,The Lord is close to the brokenhearted and sav...,0,2026-01-23T01:42:47Z,[en:0.9999957105506926]
...,...,...,...,...,...
12567,@honeydewof7975,The dislikes are payed actors >:(,47,2020-06-07T17:43:24Z,[en:0.9999974973098607]
12568,@janaashraf3978,Too tired...,4,2020-06-07T17:42:50Z,"[en:0.8571400666119778, so:0.1428581692890572]"
12569,@mattfnx-3964,firsttt,1,2020-06-07T17:42:32Z,"[en:0.8571372261146288, no:0.14286164243018612]"
12570,@AuroraVibes,*Where's everyone listening from?* ❤️\n\nYou c...,6344,2020-06-07T17:37:47Z,[en:0.9999982812727997]
12571,@AuroraVibes,"Tracklist for ""depressing songs for depressed ...",278,2020-06-07T17:35:04Z,[en:0.9999971226497227]

In [11]:
df[df['language'].notnull()].reset_index(drop=True)[1:].to_csv("rawData/youtube_comments.csv", index=False)